language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
  - rust: nightly-2017-07-01
    before_script:
    - cargo install clippy --vers 0.0.141
    script:
    - cargo clippy -- -D warnings
os:
  - linux
  - osx
